secret_key = "12345678"
log_level = "INFO"
proxy_allow_frontend = ['127.0.0.1', '::1']
session_timeout = 86400
object_storage_type = 'minio'
static_folder="static"
template_folder="templates"
app_name = "高校信息采集中心"
sms_type = "yunpian"

[db]
host = "127.0.0.1"
database = "test"
user = "root"
password = "123456"
port = 5432

[jwt]
access_token_expires = 1800
refresh_token_expires = 259200

[dev]
enabled = true
space_id = '66408226-075f-4c78-91cc-3531765623b6' # 主空间
